export const dataContainer = [
  {
    id: "1",
    name: "Zé da Tainha",
    specialties: "Black Work, Oriental",
    tattoo: "Fechamento de braço estilo oriental",
    price: 1200,
    image: require("@/images/big-Tattoo.png"),
    rating: 4.5,
    profile: require("@/images/profile.png"),
    like: true,
  },
  {
    id: "2",
    name: "Maria Manezinha",
    specialties: "Linhas finas, Natureza",
    tattoo: "Flash no Braço",
    price: 200,
    image: require("@/images/big-Tattoo2.png"),
    rating: 5.0,
    profile: require("@/images/profile2.png"),
    like: true,
  },
  {
    id: "3",
    name: "João Manezinho",
    specialties: "Linhas finas, Realismo",
    tattoo: "Retrato no braço",
    price: 800,
    image: require("@/images/big-Tattoo3.png"),
    rating: 4.9,
    profile: require("@/images/profile3.png"),
    like: false,
  },
];
